FROM gcc:latest



#COPY . /usr/test/build/

#WORKDIR /usr/test/build

#RUN ls -la /usr/test/build

RUN /home/jenkins/workspace/Pipeline_my_first_cpp_build_pipeline/my_cpp_app/build

CMD ["./HelloAppBinary"]