pipeline {
    agent { 
        node {
            label 'docker-agent-cpp'
            }
      }
    stages {
        stage('Create') {
            steps {
                echo "Creating.."
                sh '''
                  if [ ! -d "my_cpp_app/build" ]; then
                    mkdir my_cpp_app/build
                  fi                
                '''
            }
        }
        stage('Generate') {
            steps {
                echo "Generating.."
                sh '''
                  cd my_cpp_app/build
                  cmake ../source/ 
                '''
            }
        }
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                  cd my_cpp_app/build
                  make
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                  cd my_cpp_app/build

                  ./HelloAppBinary
                '''
            }
        }

        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''

                '''
            }
        }
        stage('Cleaning'){
            steps {
                echo "Cleaning.."
                sh '''
                  cd my_cpp_app/build
                  rm -rf *
                '''
            }
        }
    }
}