pipeline {
    agent { 
        node {
            label 'docker-agent-cpp'
            }
      }
    stages {
       stage('Create') {
            steps {
                echo "Creating.."
                sh '''
                  if [ ! -d "my_cpp_app/build" ]; then
                    mkdir my_cpp_app/build
                  fi                
                '''
            }
        }
        stage('Generate') {
            steps {
                echo "Generating.."
                sh '''
                  cd my_cpp_app/build
                  cmake -G"Unix Makefiles"  -D CMAKE_CXX_COMPILER=g++ ../source/ 
                '''
            }
        }
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                  cd my_cpp_app/build
                  cmake --build .
                '''
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo "Running Unit Tests.."
                sh '''
                  cd my_cpp_app/build
                  ctest
                '''
            }
        }
        stage('Test the application') {
            steps {
                echo "Testing.."
                sh '''
                  cd my_cpp_app/build
                  ./HelloAppBinary
                '''
            }
        }

        stage('Build Image') {
            steps {
                echo 'Deliver....'
                sh '''
                cd my_cpp_app/source
                docker build -t applictation_cpp_to_deploy_to_k8s .
                '''
            }
        }
    }
 /*** workspace clean up*/
  post {
    always {
      cleanWs()
    }
  }      
}