pipeline {
    agent { 
        node {
            label 'docker-agent-cpp'
            }
      }
    stages {
              stage('Copy') {
            steps {
                echo "Creating.."
                sh '''
                  echo "hello hihi" > ttest.txt
                  scp ttest.txt jenkins-blueocean:/var/jenkins_home/workspace/temp
                  fi                
                '''
            }
        }
       /* stage('Create') {
            steps {
                echo "Creating.."
                sh '''
                  if [ ! -d "my_cpp_app/build" ]; then
                    mkdir my_cpp_app/build
                  fi                
                '''
            }
        }*/
        /*
        stage('Generate') {
            steps {
                echo "Generating.."
                sh '''
                  cd my_cpp_app/build
                  cmake -G"Unix Makefiles"  -D CMAKE_CXX_COMPILER=g++ ../source/ 
                '''
            }
        }
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                  cd my_cpp_app/build
                  cmake --build .
                '''
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo "Running Unit Tests.."
                sh '''
                  cd my_cpp_app/build
                  ctest
                '''
            }
        }
        stage('Test the application') {
            steps {
                echo "Testing.."
                sh '''
                  cd my_cpp_app/build
                  ./HelloAppBinary
                '''
            }
        }

        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''

                '''
            }
      */  
    }
 /*** workspace clean up*/
  post {
    always {
      cleanWs()
    }
  }      
}