pipeline {
    agent { 
        node {
            label 'docker-agent-cpp'
            }
      }
    stages {
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                  g++ -o Test my_cpp_app/main.cpp
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                  ./my_cpp_app/Test
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''

                '''
            }
        }
    }
}